baseURL = "https://thomjiji.github.io/"
languageCode = "en-US"
title = "thomjiji"

[params]
  author = "thom"

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["$$", "$$"]]
    inline = [["$", "$"]]

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/posts/:slug/"
